### ISSUE TITLE
ucrt source, released under the MIT license!

### ISSUE THREAD

**Issue by yangyangdaji** [huangqinjin/ucrt#2]
### According to @DarkFire01 https://github.com/reactos/reactos/pull/3872#issuecomment-2106373933
![ucrt](https://github.com/huangqinjin/ucrt/assets/108261729/9b9deea5-f0f3-4237-a738-ab308d5d335a)

### 
 https://www.nuget.org/packages/Microsoft.Windows.SDK.CRTSource

**Comment by huangqinjin** [comment]
Thanks for the information, MIT license added to repo by commit https://github.com/huangqinjin/ucrt/commit/e6b58d46203d7c679238121a25373103f2f51fc6.

**Comment by yangyangdaji** [comment]
@huangqinjin It must be updated to 10.0.22621.3 nuget version to use the MIT license

see https://softwareengineering.stackexchange.com/a/264705

**Comment by huangqinjin** [comment]
I compared the nuget package and this repo, the content is identical, so no update needed.
