### ISSUE TITLE
Add a clang (not clang-cl or even maybe gcc) option for build this

### ISSUE THREAD

**Issue by trcrsired** [huangqinjin/ucrt#5]
I have this windows msvc sysroot project

https://github.com/trcrsired/windows-msvc-sysroot/tree/main

I've just seen you added CMakeLists for msvc only. Can you provide an option for using this sysroot? Thank you

**Comment by trcrsired** [comment]
https://github.com/trcrsired/llvm-releases/releases

Here is the compiler you can use.

**Comment by trcrsired** [comment]
https://github.com/llvm/llvm-project/pull/96417

I am trying to add --sysroot to clang itself

**Comment by huangqinjin** [comment]
> I have this windows msvc sysroot project
> 
> https://github.com/trcrsired/windows-msvc-sysroot/tree/main
> 
> I've just seen you added CMakeLists for msvc only. Can you provide an option for using this sysroot? Thank you

Unfortunately that doesn't include necessary headers for building UCRT. Hope the proposed sysroot layout be widely adopted by the community, at that time I might try to support it.
